KimGiWoon/1stUnityProject

Assets/CJH_Work/PlayerController.cs, Assets/CJH_Work/PlayerController.cs.meta
=> [Feat] addPlayerMove

Assets/CJH_Work/PlayerController.cs
=> [Fix] addPlayerMove

Assets/KGW_Work/CameraController.cs, Assets/KGW_Work/CameraController.cs.meta, Assets/KGW_Work/KGW_Test Scene.unity
마우스 우클릭 시 플레이어를 기준으로 움직이도록 구현했습니다.
=> [Feat] Add Camera Move

Assets/BIK_Work/BIK_Test Scene.unity, Assets/BIK_Work/Blue.mat, Assets/BIK_Work/Blue.mat.meta, Assets/BIK_Work/Red.mat, Assets/BIK_Work/Red.mat.meta
=> [Feat] Add Map

Assets/BJW_Work/HammerHead.mat, Assets/BJW_Work/HammerHead.mat.meta, Assets/BJW_Work/Map.unity, Assets/BJW_Work/Map.unity.meta, Assets/Scenes.meta, Assets/Scenes/SampleScene.unity, Assets/Scenes/SampleScene.unity.meta, ProjectSettings/ProjectSettings.asset
=> [Feat]Add Map Num7~9

Assets/BIK_Work/Object_Pandulum.prefab, Assets/BIK_Work/Object_Pandulum.prefab.meta, Assets/BIK_Work/PandulumMovement.cs, Assets/BIK_Work/PandulumMovement.cs.meta
=> [Feat] Add Object - Pandulum

Assets/CJH_Work/PlayerGrab.cs, Assets/CJH_Work/PlayerGrab.cs.meta
=> [Feat] addPlayerGrab

Assets/BJW_Work/BJW_Test Scene.unity, Assets/BJW_Work/Ice.mat, Assets/BJW_Work/Ice.mat.meta, Assets/BJW_Work/IceTile.cs, Assets/BJW_Work/IceTile.cs.meta, Assets/BJW_Work/IceTile.prefab, Assets/BJW_Work/IceTile.prefab.meta, Assets/BJW_Work/New Physic Material.physicMaterial, Assets/BJW_Work/New Physic Material.physicMaterial.meta, Assets/BJW_Work/SlimeTile.cs, Assets/BJW_Work/SlimeTile.cs.meta, Assets/BJW_Work/SlimeTile.prefab, Assets/BJW_Work/SlimeTile.prefab.meta, Assets/BJW_Work/SlowTile.cs, Assets/BJW_Work/SlowTile.cs.meta, Assets/BJW_Work/SlowTile.mat, Assets/BJW_Work/SlowTile.mat.meta, Assets/BJW_Work/TestPlayer.cs, Assets/BJW_Work/TestPlayer.cs.meta, ProjectSettings/TagManager.asset
=> [Add Object]Ice and Slime Tile

Assets/KGW_Work/CameraController.cs, Assets/KGW_Work/KGW_Test Scene.unity
카메라 시점 위.아래 이동 마우스의 드래그 방향과 카메라 시점이 반대 방향으로 움직여 같은 방향으로 이동하게 수정
=> [Fix] Camera Move Correction

Assets/BIK_Work/PlayerprefsManager.cs, Assets/BIK_Work/PlayerprefsManager.cs.meta
싱글톤으로 구성된 데이터를 저장하는 PlayerprefsManager 추가
=> [Feat] Add PlayerprefsManager

Assets/KGW_Work/CameraController.cs, Assets/KGW_Work/KGW_Test Scene.unity
마우스 우클릭이 아닌 커서 이동으로 카메라의 화면이 이동하도록 수정하였고 줌인, 줌아웃 기능 추가
=> [Fix] Camera Move Action Correction

Assets/CJH_Work/GameManager.cs
=> [Feat] addGameManager

.editorconfig, Assets/LSW_Work/01. Scene/LSW_Test Scene.unity, Assets/LSW_Work/02. Script/PlayerController(LSW).cs, Assets/LSW_Work/02. Script/PlayerController(LSW).cs.meta, Assets/LSW_Work/04. Materials/New Physic Material 3.physicMaterial, Assets/LSW_Work/04. Materials/New Physic Material 3.physicMaterial.meta
플레이어에 적용된 physics material 변경
인코딩 방식 UTF -8  통일
=> [Fix] Change physics material in player

Assets/CJH_Work/Scripts/GameManager.cs, Assets/CJH_Work/Scripts/GameManager.cs.meta, Assets/CJH_Work/Scripts/Player.cs, Assets/CJH_Work/Scripts/Player.cs.meta, Assets/CJH_Work/Scripts/PlayerController.cs, Assets/CJH_Work/Scripts/PlayerController.cs.meta, Assets/CJH_Work/Scripts/PlayerGrab.cs, Assets/CJH_Work/Scripts/PlayerGrab.cs.meta
=> [Feat] Player and GameManager

Assets/LSW_Work/PlayerAnimator.controller, Assets/LSW_Work/PlayerAnimator.controller.meta
=> [Chore] Add player animation file

Assets/KGW_Work/ClearSceneUI.cs, Assets/KGW_Work/FinishPoint.cs, Assets/KGW_Work/SaveManager.cs
=> [Chore] Save Manager Correction 1/2

Assets/BJW_Work/Script/AudioMixController.cs, Assets/BJW_Work/Script/AudioMixController.cs.meta, Assets/BJW_Work/Script/MouseLook.cs, Assets/BJW_Work/Script/MouseLook.cs.meta, Assets/BJW_Work/Script/MouseSensitivityManager.cs, Assets/BJW_Work/Script/MouseSensitivityManager.cs.meta, Assets/BJW_Work/Script/SettingController.cs, Assets/BJW_Work/Script/SettingController.cs.meta, Assets/BJW_Work/Script/SoundOption.cs, Assets/BJW_Work/Script/SoundOption.cs.meta
=> [Feat] Add Script(Title and Option)

Assets/01.Scenes/TitleScene.unity, Assets/BIK_Work/ButtonController.cs, Assets/BIK_Work/ButtonController.cs.meta, Assets/BIK_Work/SceneManager.cs, ProjectSettings/EditorBuildSettings.asset
=> [Feat] Add GameManager to TitleScene

Assets/CJH_Work/Scripts/PlayerController.cs
=> [Fix] PlayerMove

Assets/KGW_Work/ClearSceneUI.cs, Assets/KGW_Work/FinishPoint.cs, Assets/KGW_Work/RankView.prefab, Assets/KGW_Work/RankView.prefab.meta, Assets/KGW_Work/SaveManager.cs, Assets/KGW_Work/Scene/ClearScene.unity
클리어 씬에서 세이브 매니저에 플레이어 이름과 시간을 저장하고 랭킹보드 구현 ( 세이브 버튼 단 1회 클릭 )
=> [Feat] Add Save Manager, Clear Scene

Assets/CJH_Work/Player Variant 1.prefab, Assets/CJH_Work/Player Variant 1.prefab.meta, Assets/CJH_Work/Scripts/PlayerController.cs, Assets/CJH_Work/Scripts/PlayerGrab.cs
=> [Fix] PlayerAct

Assets/LSW_Work/01. Scene/InGameScene.unity, Assets/LSW_Work/02. Script/WaterMovement.cs, Assets/LSW_Work/CameraControllerLSW.cs, Assets/LSW_Work/GameClear.cs, Assets/LSW_Work/GameClear.cs.meta
=> [Feat] Add gameclear spot, gameover setting

Assets/CJH_Work/Scripts/GameManager.cs, Assets/CJH_Work/Scripts/PlayerController.cs, Assets/CJH_Work/Scripts/PlayerGrab.cs, ProjectSettings/TagManager.asset
=> [Feat] PlayerAct

Assets/01.Scenes/ClearScene.unity, Assets/01.Scenes/TitleScene.unity, Assets/KGW_Work/RankButtonClick.cs, Assets/KGW_Work/Scripts/ClearSceneUI.cs, Assets/KGW_Work/Scripts/SaveManager.cs, Assets/LSW_Work/GameClear.cs, Assets/LSW_Work/PlayTimeCalculate.cs, ProjectSettings/EditorBuildSettings.asset
타이틀 씬의 랭크보드 출력 데이터 글씨 크기 및 간격 수정, 인게임씬 게임시간 출력 수정, 클리어시 게임클리어 시간 미저장 이슈로 수정
=> [Fix] Title Scene, InGame Scene Correction

Assets/02.Scripts/Player Controller/PlayerGrab.cs
=> [Fix] PlayerGrab

Assets/01.Scenes/TitleScene.unity, Assets/02.Scripts/Game Manager/BGMManager.cs, Assets/02.Scripts/Game Manager/SettingsControl.cs
Bgm슬라이더가 게임 시작하면 초기값으로 돌아가던 버그 수정
=> [Fix] BgmSlider

Assets/01.Scenes/TitleScene.unity, Assets/02.Scripts/Game Manager/BGMManager.cs, Assets/02.Scripts/Game Manager/SettingsControl.cs
스크롤바 이동거리 리미트 관련 스크립트가 적용되지 않아 다시 PR합니다.
=> [Fix] Scrollbar Move Re Correction

Assets/01.Scenes/OptionScene.unity
슬라이드바에서 핸들 클릭시 약간 옆으로 움직이는 버그 현상 수정
=> [Fix] Slider Teleport

Assets/01.Scenes/InGameScene.unity, Assets/02.Scripts/Object Controller/TriggerZone.cs, Assets/02.Scripts/Player Controller/PlayerController.cs, Assets/02.Scripts/Player Controller/PlayerGrab.cs, Assets/03.Prefabs/Object Prefabs/Pencil.prefab, Assets/03.Prefabs/Object Prefabs/Pencil.prefab.meta
=> [Feat] TriggerZone

Assets/01.Scenes/TitleScene.unity
슬라이더바 핸들 클릭시 약간 옆으로 이동하던 현상 재수정
=> [Fix] SliderBar

Assets/02.Scripts/Object Controller/TriggerZone.cs, Assets/02.Scripts/Player Controller/PlayerGrab.cs
=> [Fix] BugFix

Assets/02.Scripts/Player Controller/PlayerGrab.cs
=> [Fix] Change grab key
